### PR TITLE
Update deauth.ino

### LINKED ISSUE #3: Implement updated changes from other fork
As per https://github.com/willemwouters/esp8266-injection-example

### PR DESCRIPTION
**Pull request by quantum-x**
@imayoda I can't test the changes at present (currently travelling)
Could you please test, and if all is well, feel free to merge the pull request.

Should close #3 

Thanks!

### CODE REVIEW

**Comment by imayoda** [comment]
it gives same behaviour as original, but going very fast now.
sometims works sometimes not, i'm serial printing ap client and channel but 99,9999999% of the time, nothing happens to aps and clients. Going to investigate the time esp8266 needs to execute the wifi code, beside the user code.. i think it's there the problem as they say in reference https://github.com/esp8266/Arduino/blob/master/doc/reference.md#timing-and-delays

**Comment by quantum-x** [comment]
This is quite possibly why the delay(500) in the loop() method aided stability?

**Comment by imayoda** [comment]
I belive main problem is that the code doesn't work good in arduino method.. we should not use at all internal timers and manage everything in loop, i'm doing experiments this way.
Original code was pushing a delay() every 5000 millis, then commited to 10 millis (the right timing in my opinion to have enough packets going). Then there was the loop that called again every 500millis, with some hangs after some time with wdt reset reason.
Main problem is that esp's delay() isn't blocking so external timed function worked in delayed loop, colliding after some time values from timed deauth with delayed deauth.
I'll try to put everything in loop, sniffing plus deauthing and see what happens.

**Comment by imayoda** [comment]
don't know what's wrong, but i can't get any deauth against my clients (maybe too many aps around).. 
I'm out of immagination right now.
Did you ever get a client deauthed with first commit method? i realize right now that I haven't seen yet a solid result from this code.
Last try will be with defined hardcoded ap and client..

**Comment by quantum-x** [comment]
The initial commit worked perfectly for me.
It would take a few seconds to hit the right channel, but I was definitely
deauthed.

Perhaps it was the watchdog timer not working, and it was indeed the
deauth() call in the loop() that was working...

**Comment by quantum-x** [comment]
There is also a version here that seems to only use standard arduino calls:

https://github.com/RandDruid/esp8266-deauth/blob/master/DeAuth/DeAuth.ino

**Comment by imayoda** [comment]
original version (including polkin's) had no option for channel selection, it was declared and never incremented.
New version from RandDruid is neat. Did some chat with esp8266 arduino pros, they are telling us that in arduino style, the loop() is already hooked inside main esp running code (with given priority), so the use of timers should be unnecessary (except for long blocking code).
Going to test and tell :)

**Comment by imayoda** [comment]
discovered now the mess they made with freedom packet, not working at all in latest sdk.. had to change to older version and things are going good now.
https://hackaday.io/post/30838

**Comment by quantum-x** [comment]
Yeah, 1.6.7 is bad :)

**Comment by vinorasu** [comment]
hi, imayoda and quantum-x,
please I need some info here:
I have IDE 1.65 + esp8266 2.1.0-rc2 but the freedom packet returns -1 as it has been disabled for management packets by Expressif

how did you took the "non limited"  wifi_send_pkt_freedom   function from the old sdk13 version? I mean which files in the arduino IDE +ESP8266 did you modify  or copy  to make it work? 
thanks in advance for the help.

**Comment by imayoda** [comment]
Just install in boards manager the oldest you find

**Comment by quantum-x** [comment]
I'd used 2.0RC1 - which seems to work perfectly.

**Comment by vinorasu** [comment]
hi, imayoda and quantum-x,
issue fixed , with the 2.0.0 it works,  thanks both  for the reply :-)

**Pull request merged**
